kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: pacman-route
  namespace: pacman
  labels:
    name: pacman
spec:
  to:
    kind: Service
    name: pacman
  host: pacman-pacman.apps.ocp4gcp.4mfn.p2.openshiftapps.com
  port:
    targetPort: 8080
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None